apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployconversaotemperatura
spec:
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:    
      containers:
      - name: conversaotemperatura
        image: zanryuga/conversao-temperatura:v1          
        ports:
        - containerPort: 8080      

---

apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

